### ISSUE TITLE
Not all time representation formats are supported

### ISSUE THREAD

**Issue by Alexander-Orlovsky** [SGroe/gpx-segment-importer#4]
If in the GPX source file the **\<time\> tag** is presented in the format "2022-01-02T10:07:13**Z**" (at the end of "Z"), then the algorithm 'Import GPX segments' successfully calculates the fields "_duration" and "_speed" (with the option "calculate motion attributes" enabled)

If the presentation format is 2023-10-15T14:58:34+03:00 (at the end "+03:00"), then the values for the fields "_duration" and "_speed" remain NULL. But this time format is formed by some GPS-trackers.

Of course, I can first add a track to QGIS as a point layer (without using your wonderful plugin), and then execute the algorithm 'Create track segments'.

But I think this is a reason to think about how to make your plugin even more perfect.  
Ideally, I would like the algorithm 'Import GPX segments' to be able to handle all formats for Time provided by the ISO 8601 standard.

**Comment by SGroe** [comment]
Hi @Alexander-Orlovsky, thank you for your message. 
Fyi, I will publish an new version soon.

**Comment by Alexander-Orlovsky** [comment]
This is great news for me and my students.
We are looking forward to the new version.

**Comment by SGroe** [comment]
@Alexander-Orlovsky: I have uploaded an experimental version 2.6 that includes this improvement. I invite you to give this version a try and give feedback here.
