### ISSUE TITLE
startup problem with GPX plugin (both stable and experimental versions)  at QGIS startup (3.36.3)

### ISSUE THREAD

**Issue by jimseamapping** [SGroe/gpx-segment-importer#5]
Hi

I've been getting an error from the GPX importer (both current and experimental versions) at QGIS (3.36.3) startup time. 

The error is:
--------------------------------------------------------------------------------------------------
TypeError: QgsProcessingParameterFile(): arguments did not match any overloaded call:
              overload 1: argument 3 has unexpected type 'int'
              overload 2: argument 1 has unexpected type 'str'
             
2024-05-31T20:18:05     WARNING    Traceback (most recent call last):
              File "C:\Users/qubit/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GpxSegmentImporter\processing\gpx_segment_importer_algorithm.py", line 91, in initAlgorithm
              self.addParameter(QgsProcessingParameterFile(self.INPUT, self.tr('Input gpx file'),

------------------------------------------------------------------------------------------------------
Could this be a python error in the version differences ?   

Or does the GPX importer have other dependencies I missed_ ?

thanks in advance
Jim

**Comment by SGroe** [comment]
Hi @jimseamapping, thank you for raising this issue. The import of QgsProcessingParameterFile.Behavior.File has changed in QGIS 3.36.
I have just released a new version v3.1. Please head to the releases page on this repository and download the attached ZIP. Can you please give me some feedback if it works properly for you! Afterwards I will publish it in the QGIS plugin repo.

**Comment by jimseamapping** [comment]
Hi Simon -

I will do that.

I want to be sure I am doing this correctly - the new zip file (file tree)
should be used to over write the old gpx plugin tree in the QGIS hierarchy?

I am on a windows platform fyi.

thanks
Jim Seagraves

**Comment by SGroe** [comment]
In QGIS, go to the menu "Plugins" and select "Manage and install plugins..." > "Install from ZIP", select the ZIP file and click "Install plugin"

**Comment by jimseamapping** [comment]
Hi Simon

It worked.  This was version 3.1 zip file.

Thanks for updating the plugin
Jim Seagraves
