### ISSUE TITLE
distance calculation is in degree

### ISSUE THREAD

**Issue by Jacques10967** [SGroe/gpx-segment-importer#7]
I am using version 3.2 of your plugin with QGIS 3.38.0-Grenoble.
When importing a GPX file and activating "Calculate motion attributes..." the calculated distance is not of much use as it is in degrees.

The reason seems to be:
In the method GeomTools::distance(...) the call to
distance.setEllipsoid(distance.sourceCrs().ellipsoidAcronym()
fails, with sourceCrs().ellipsoidAcronym() == EPSG:7030
As a result the distance is now returned in degrees.

When replacing the calls to GeomTools::distance with GeomTools::distance_andoyer everything works fine.

So I am wondering if you could call GeomTools::distance_andoyer by default in your next release of the plugin.

Thanks

Jacques

**Comment by SGroe** [comment]
Hi @Jacques10967, I cannot reproduce this. Which CRS has your input layer? And which CRS has your project?

**Comment by SGroe** [comment]
> So I am wondering if you could call GeomTools::distance_andoyer by default in your next release of the plugin.

I want to avoid this due to the limited accuracy.

**Comment by Jacques10967** [comment]
Hi @SGroe. Thanks for looking into this.
My input is a gpx file from my hard drive and has no CRS applied, but gets one in import_gpx_file (EPSG:4326)
My project CRS is EPSG:3857 (WGS 84 / Pseudo-Mercartor)

I have added some prints in the _distance method:_
```
        if crs is not None:
            distance.setSourceCrs(crs, QgsProject.instance().transformContext())
            if distance.sourceCrs().isGeographic():
                print(distance.sourceCrs().ellipsoidAcronym())
                if distance.setEllipsoid(distance.sourceCrs().ellipsoidAcronym()):
                    print(distance.willUseEllipsoid())
                else:
                    print ("set failed")    
```
The result is:
```
EPSG:7030
set failed
```

**Comment by Jacques10967** [comment]
I did some further digging and realized, that under Project->Properties->General I have "None/Planimetric" set for Measurements.
![image](https://github.com/user-attachments/assets/5e72b2a6-47d6-463b-94db-035d9e4cac03)
According to the QGIS documentation [https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#general-properties] I should be able to choose an existing ellipsoid from a predefined list.
However as one can see from the screen shot the drop-down  does not provide such a list.

I am wondering how this looks in your version of QGIS

**Comment by SGroe** [comment]
> I am wondering how this looks in your version of QGIS

I see a long list of available ellipsoids here.

**Comment by Jacques10967** [comment]
Hi @SGroe.  Just to let you know.
I could solve this (my) issue with the GpxSegmentImporter.
I had a "proj.db" from an older proj installation in my search path, and this one was obviously too old for the current version of QGIS. This was also the reason why did not have any ellipsoids in this drop-down. 
After upgrading the "proj.db" everything works now as expected with GpxSegmentImporter.

Thanks for this great and useful plugin

Jacques
